### PR TITLE
fix: Only add Redis instrumentation if connection found in DI

### LINKED ISSUE #322: AddAutoInstrumentations fails due to missing config for AddRedisInstrumentation
I registered with Honeycomb and followed the onboarding instructions, which is the same as in the [OpenTelemetry for .NET documentation](https://docs.honeycomb.io/getting-data-in/opentelemetry/dotnet-distro/#initialize). No information was written to Honeycomb. So I next pulled down and tried the [example aspnetcore project](https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/tree/main/examples/aspnetcore). This worked. I narrowed down the difference between this working project and the non working project. I determined that the non working solution was failing because of [`AddRedisInstrumentation`](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/355643cf5be993fe055d62b0f9121b46531a063c/src/OpenTelemetry.Instrumentation.StackExchangeRedis/TracerProviderBuilderExtensions.cs#L65) in [`AddAutoInstrumentations`](https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/blob/c0237661da66e95757a303ba7cc48e356e2d3001/src/Honeycomb.OpenTelemetry.AutoInstrumentations/TracerProviderBuilderExtensions.cs#L32).

Either `AddRedisInstrumentation` should be removed from `AddAutoInstrumentations` or the documentation should be updated to include the additional configuration needed for Redis, like in [its documentation](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/8d3510ac6b0a90e5fe8ac913dec3565d3fba85e2/src/OpenTelemetry.Instrumentation.StackExchangeRedis/README.md?plain=1#L56) or in the [example aspnetcore-redis project](https://github.com/honeycombio/honeycomb-opentelemetry-dotnet/blob/127a8d64b79a2694e08219cece81e96b47365593/examples/aspnetcore-redis/Program.cs#L7-L14).

**Versions**

- .NET 6.0.403
- Honeycomb.OpenTelemetry 1.2.0
- Honeycomb.OpenTelemetry.AutoInstrumentations 0.26.0-beta

**Steps to reproduce**

In _Program.cs_ configure tracing:
```csharp
var honeycombOptions = builder.Configuration.GetHoneycombOptions();
builder.Services.AddOpenTelemetryTracing(otelBuilder =>
    otelBuilder
        .AddHoneycomb(honeycombOptions)
        .AddAutoInstrumentations());
```
No Activities are written to Honeycomb and no error information is surfaced, from what I observed.

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
## Which problem is this PR solving?
Apps that do not utilise Redis and register a connection before calling `AddAutoInstrumentations` fail to send telemetry. This is because even though the `AddRedisInstrumentation` call has the connection as an optional parameter, an exception is thrown if a connection is not provided and one cannot be found in DI.

This PR updates `AddAutoInstrumentations` to try to find a Redis connection from DI and only call `AddRedisInstrumentation` if one is found.

- Closes #322

## Short description of the changes
- Only add Redis instrumentation if a registered Redis connection is found using DI

### CODE REVIEW

File: src/Honeycomb.OpenTelemetry.AutoInstrumentations/TracerProviderBuilderExtensions.cs [hunk 1]
```diff
@@ -14,6 +15,19 @@ public static class TracerProviderBuilderExtensions
         /// <returns>The instance of <see cref="TracerProviderBuilder"/> to chain the calls.</returns>
         public static TracerProviderBuilder AddAutoInstrumentations(this TracerProviderBuilder builder)
         {
+            // Only add Redis instrumentation if we can find a Redis connection in DI
+            if (builder is IDeferredTracerProviderBuilder deferredBuilder)
+            {
+                deferredBuilder.Configure((sp, b) =>
+                {
+                    var connection = (IConnectionMultiplexer)sp.GetService(typeof(IConnectionMultiplexer));
```
Comment (cartermp) [inline src/Honeycomb.OpenTelemetry.AutoInstrumentations/TracerProviderBuilderExtensions.cs:23]: This will throw an exception if the cast fails - is that a likely scenario? If not then I suppose this is fine, but using `as` will avoid an exception.

**Review by JamieDanielson — COMMENTED** [review]
Hmm, I'm still having trouble even after this change.

I used the aspnetcore example app, and on its own with `.AddAspNetCoreInstrumentationWithBaggage()` it sends a trace with 2 spans. When I swap that out with `.AddAutoInstrumentations()`, it does not send any traces.

I [enabled diagnostics](https://docs.honeycomb.io/getting-data-in/opentelemetry/dotnet-distro/#error-log) by setting up a file for `OTEL_DIAGNOSTICS.json`. In the error log I see the following:

```log
2022-11-21T15:45:01.0061910Z:An exception occurred while retrieving OpenTelemetry Tracer. OpenTelemetry tracing will remain disabled. Exception: '{0}'.{System.InvalidOperationException: StackExchange.Redis IConnectionMultiplexer could not be resolved through application IServiceProvider
   at OpenTelemetry.Trace.TracerProviderBuilderExtensions.<>c__DisplayClass0_0.<AddRedisInstrumentation>b__0(IServiceProvider sp, TracerProviderBuilder builder)

...
```

**Comment by MikeGoldsmith** [comment]
I followed the same steps as you @JamieDanielson and my app continued to send telemetry - not sure what else was different
